# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "geerlingguy/centos7"

  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.galaxy_command = "ansible-galaxy install --role-file=%{role_file}"
    ansible.galaxy_role_file = "roles.yml"
    ansible.playbook = "playbook.yml"
    ansible.become = true
  end
end
